# 載入 sqlContext 函式庫

In [1]:
from pyspark.sql import SQLContext, SparkSession
from pyspark import SparkContext, SparkConf

sparkConf = SparkConf().setMaster("local") \
            .setAppName("read-mongodb-2") 
            
sc = SparkContext(conf=sparkConf)
sqlContext = SQLContext(sc)

# 設定遠端 Mongodb 連線資訊

In [2]:
df = sqlContext.read.format("com.mongodb.spark.sql.DefaultSource")\
                    .option("spark.mongodb.input.uri", "mongodb://mongodb:27017/ltu_demo.data_2019063020").load()

# 打印 SQLContext Dataframe 第一筆資料內容

In [3]:
df.first()

Row(Humidity=66, Temperature=27.0, _id=Row(oid='5d1b8d40be567be7cc90353b'), device_id='001', timestamp='2019-07-03 00:37:12')

# 將 Dataframe 轉換為 Spark rdd 格式

In [4]:
rdd = df.rdd

# 打印 Spark rdd 第一筆資料內容
## 後續接 Spark RDD 課程

In [5]:
rdd.first()

Row(Humidity=66, Temperature=27.0, _id=Row(oid='5d1b8d40be567be7cc90353b'), device_id='001', timestamp='2019-07-03 00:37:12')

# 抓出 temperature = 27

In [7]:
df[df["temperature"]==27].show()

+--------+-----------+--------------------+---------+-------------------+
|Humidity|Temperature|                 _id|device_id|          timestamp|
+--------+-----------+--------------------+---------+-------------------+
|      66|       27.0|[5d1b8d40be567be7...|      001|2019-07-03 00:37:12|
|      66|       27.0|[5d1b8d40be567be7...|      001|2019-07-03 00:41:30|
|      64|       27.0|[5d1b8d40be567be7...|      001|2019-07-03 00:42:47|
|      64|       27.0|[5d1b8d40be567be7...|      001|2019-07-03 00:44:49|
|      64|       27.0|[5d1b8d40be567be7...|      001|2019-07-03 00:45:10|
|      63|       27.0|[5d1b8d40be567be7...|      001|2019-07-03 00:45:51|
|      64|       27.0|[5d1b8d40be567be7...|      001|2019-07-03 00:46:43|
|      65|       27.0|[5d1b8d40be567be7...|      001|2019-07-03 00:47:24|
|      65|       27.0|[5d1b8d40be567be7...|      001|2019-07-03 00:47:35|
|      67|       27.0|[5d1b8d40be567be7...|      001|2019-07-03 00:48:42|
|      67|       27.0|[5d1b8d40be567be7...|      001|2019-07-03 00:49:13|
|      67|       27.0|[5d1b8d40be567be7...|      001|2019-07-03 00:49:23|
|      66|       27.0|[5d1b8d40be567be7...|      001|2019-07-03 00:49:38|
|      66|       27.0|[5d1b8d40be567be7...|      001|2019-07-03 00:49:43|
|      66|       27.0|[5d1b8d40be567be7...|      001|2019-07-03 00:50:40|
|      65|       27.0|[5d1b8d40be567be7...|      001|2019-07-03 00:51:26|
|      65|       27.0|[5d1b8d40be567be7...|      001|2019-07-03 00:52:28|
|      65|       27.0|[5d1b8d40be567be7...|      001|2019-07-03 00:52:33|
|      65|       27.0|[5d1b8d40be567be7...|      001|2019-07-03 00:52:38|
|      65|       27.0|[5d1b8d40be567be7...|      001|2019-07-03 00:52:49|
+--------+-----------+--------------------+---------+-------------------+
only showing top 20 rows

# 將 Dataframe 轉換成 pandas Dataframe格式

In [8]:
pandas_df=df.toPandas()

# 增加一筆資料

In [9]:
pandas_df["operator"]="Andy"

# 打印 pandas_df 資料內容

In [10]:
pandas_df

,Humidity,Temperature,_id,device_id,timestamp,operator
0,66,27.0,"(5d1b8d40be567be7cc90353b,)",001,2019-07-03 00:37:12,Andy
1,66,27.0,"(5d1b8d40be567be7cc90353c,)",001,2019-07-03 00:41:30,Andy
2,64,27.0,"(5d1b8d40be567be7cc90353d,)",001,2019-07-03 00:42:47,Andy
3,64,27.0,"(5d1b8d40be567be7cc90353e,)",001,2019-07-03 00:44:49,Andy
4,64,27.0,"(5d1b8d40be567be7cc90353f,)",001,2019-07-03 00:45:10,Andy
5,63,27.0,"(5d1b8d40be567be7cc903540,)",001,2019-07-03 00:45:51,Andy
6,64,27.0,"(5d1b8d40be567be7cc903541,)",001,2019-07-03 00:46:43,Andy
7,65,27.0,"(5d1b8d40be567be7cc903542,)",001,2019-07-03 00:47:24,Andy
8,65,27.0,"(5d1b8d40be567be7cc903543,)",001,2019-07-03 00:47:35,Andy
9,67,27.0,"(5d1b8d40be567be7cc903544,)",001,2019-07-03 00:48:42,Andy
10,67,27.0,"(5d1b8d40be567be7cc903545,)",001,2019-07-03 00:49:13,Andy
11,67,27.0,"(5d1b8d40be567be7cc903546,)",001,2019-07-03 00:49:23,Andy
12,66,27.0,"(5d1b8d40be567be7cc903547,)",001,2019-07-03 00:49:38,Andy
13,66,27.0,"(5d1b8d40be567be7cc903548,)",001,2019-07-03 00:49:43,Andy
14,66,27.0,"(5d1b8d40be567be7cc903549,)",001,2019-07-03 00:50:40,Andy
15,65,27.0,"(5d1b8d40be567be7cc90354a,)",001,2019-07-03 00:51:26,Andy
16,65,27.0,"(5d1b8d40be567be7cc90354b,)",001,2019-07-03 00:52:28,Andy
17,65,27.0,"(5d1b8d40be567be7cc90354c,)",001,2019-07-03 00:52:33,Andy
18,65,27.0,"(5d1b8d40be567be7cc90354d,)",001,2019-07-03 00:52:38,Andy
19,65,27.0,"(5d1b8d40be567be7cc90354e,)",001,2019-07-03 00:52:49,Andy
20,65,27.0,"(5d1b8d40be567be7cc90354f,)",001,2019-07-03 00:53:04,Andy
21,64,27.0,"(5d1b8d40be567be7cc903550,)",001,2019-07-03 00:53:14,Andy
22,64,27.0,"(5d1b8d40be567be7cc903551,)",001,2019-07-03 00:53:55,Andy
23,64,27.0,"(5d1b8d40be567be7cc903552,)",001,2019-07-03 00:54:27,Andy
24,64,27.0,"(5d1b8d40be567be7cc903553,)",001,2019-07-03 00:55:49,Andy
25,64,27.0,"(5d1b8d40be567be7cc903554,)",001,2019-07-03 00:56:15,Andy
26,64,27.0,"(5d1b8d40be567be7cc903555,)",001,2019-07-03 00:56:56,Andy
27,63,27.0,"(5d1b8d40be567be7cc903556,)",001,2019-07-03 00:57:16,Andy
28,64,27.0,"(5d1b8d40be567be7cc903557,)",001,2019-07-03 00:57:21,Andy
29,64,27.0,"(5d1b8d40be567be7cc903558,)",001,2019-07-03 00:58:33,Andy
...,...,...,...,...,...,...
137,66,27.0,"(5d1b8d58be567be7cc9035c4,)",001,2019-07-03 00:59:04,Andy
138,66,27.0,"(5d1b8d68be567be7cc9035c5,)",001,2019-07-03 00:59:19,Andy
139,66,27.0,"(5d1b8d6dbe567be7cc9035c6,)",001,2019-07-03 00:59:25,Andy
140,67,27.0,"(5d1b8d77be567be7cc9035c7,)",001,2019-07-03 00:59:35,Andy
141,67,27.0,"(5d1b8d7cbe567be7cc9035c8,)",001,2019-07-03 00:59:40,Andy
142,67,27.0,"(5d1b8d8cbe567be7cc9035c9,)",001,2019-07-03 00:59:55,Andy
143,67,27.0,"(5d1b8d96be567be7cc9035ca,)",001,2019-07-03 01:00:06,Andy
144,67,27.0,"(5d1b8da0be567be7cc9035cb,)",001,2019-07-03 01:00:16,Andy
145,67,27.0,"(5d1b8da5be567be7cc9035cc,)",001,2019-07-03 01:00:21,Andy
146,67,27.0,"(5d1b8daabe567be7cc9035cd,)",001,2019-07-03 01:00:26,Andy
147,67,27.0,"(5d1b8dbabe567be7cc9035ce,)",001,2019-07-03 01:00:41,Andy
148,67,27.0,"(5d1b8dbfbe567be7cc9035cf,)",001,2019-07-03 01:00:47,Andy
149,67,27.0,"(5d1b8dc9be567be7cc9035d0,)",001,2019-07-03 01:00:57,Andy
150,67,27.0,"(5d1b8dcebe567be7cc9035d1,)",001,2019-07-03 01:01:02,Andy
151,67,27.0,"(5d1b8dd8be567be7cc9035d2,)",001,2019-07-03 01:01:12,Andy
152,67,27.0,"(5d1b8ddebe567be7cc9035d3,)",001,2019-07-03 01:01:17,Andy
153,67,27.0,"(5d1b8de3be567be7cc9035d4,)",001,2019-07-03 01:01:23,Andy
154,67,27.0,"(5d1b8dedbe567be7cc9035d5,)",001,2019-07-03 01:01:33,Andy
155,67,27.0,"(5d1b8df2be567be7cc9035d6,)",001,2019-07-03 01:01:38,Andy
156,67,27.0,"(5d1b8df7be567be7cc9035d7,)",001,2019-07-03 01:01:43,Andy
157,67,27.0,"(5d1b8dfdbe567be7cc9035d8,)",001,2019-07-03 01:01:48,Andy
158,66,27.0,"(5d1b8e07be567be7cc9035d9,)",001,2019-07-03 01:01:59,Andy
159,66,27.0,"(5d1b8e0cbe567be7cc9035da,)",001,2019-07-03 01:02:04,Andy
160,66,27.0,"(5d1b8e11be567be7cc9035db,)",001,2019-07-03 01:02:09,Andy
161,66,27.0,"(5d1b8e16be567be7cc9035dc,)",001,2019-07-03 01:02:14,Andy
162,66,27.0,"(5d1b8e1cbe567be7cc9035dd,)",001,2019-07-03 01:02:19,Andy
163,66,27.0,"(5d1b8e2bbe567be7cc9035de,)",001,2019-07-03 01:02:35,Andy
164,66,27.0,"(5d1b8e3abe567be7cc9035df,)",001,2019-07-03 01:02:50,Andy
165,66,27.0,"(5d1b8e4abe567be7cc9035e0,)",001,2019-07-03 01:03:05,Andy
166,65,27.0,"(5d1b8e54be567be7cc9035e1,)",001,2019-07-03 01:03:16,Andy

In [11]:
sc.stop()